### ISSUE TITLE
Move test under dev_dependencies

### ISSUE THREAD

**Issue by awhitford** [niinyarko/flutter-international-phone-input#17]
The [`test`](https://github.com/niinyarko/flutter-international-phone-input/blob/master/pubspec.yaml#L14) dependency should be moved from `dependencies ` to `dev_dependencies`.  (Isn't it only for _testing_, and not a _runtime_ dependency?)

**Comment by niinyarko** [comment]
@awhitford you are right this has been moved 🙇
