### ISSUE TITLE
Dark mode support

### ISSUE THREAD

**Issue by almodoen** [niinyarko/flutter-international-phone-input#6]
just replace `Colors.white` in input_widget.dart ...

with this:
`MediaQuery.of(context).platformBrightness == Brightness.dark ? Color(0xff212121) : Colors.white`

for dark mode ..

**Comment by almodoen** [comment]
or comment this lines of code
`backgroundColor: Colors.transparent,`
`color: Colors.white,`
like this:
`//backgroundColor: Colors.transparent,`
`//color: Colors.white,`

**Comment by niinyarko** [comment]
@almodoen there is no `input_widget.dart` in this project.
