### ISSUE TITLE
Suggestions ..

### ISSUE THREAD

**Issue by almodoen** [niinyarko/flutter-international-phone-input#7]
1. try to make (const widgets list of the countries) instead of building (the countries list) every time we press the button , it will make the plugin very fast , and improve the performance of the app ..

2. add auto detect country code using (Location service) .. , i can help .., but i never developed a plugin , and don't know how to upload it ..

3. in the filed using this code will deted the system country code (imported from dart:io package)
`initialCountry2LetterCode: Platform.localeName.split('_')[1].toString()`

**Comment by niinyarko** [comment]
Your suggestions are noted 🙇
