### ISSUE TITLE
No labelText Option

### ISSUE THREAD

**Issue by drakebw** [niinyarko/flutter-international-phone-input#8]
I would like to add a label to the TextField widget in the InternationalPhoneInput widget. Allowing a positional parameter to pass in an optional labelText would add this feature quite easily

**Comment by drakebw** [comment]
I forked the repository and added a simple fix to this issue. The pull request can be found [here](https://github.com/niinyarko/flutter-international-phone-input/pull/9).

**Comment by niinyarko** [comment]
Thank you @drakebw. This is merged.
